import type { Product, ProductImage } from "./types";

/*
 * SAMPLE CATALOG
 *
 * These products demonstrate every field the storefront supports. They are
 * flagged `sample: true` and must be replaced with your actual merchandise —
 * with specifications verified against the physical goods and real
 * photography — before launch. `npm run check:launch` enforces this.
 *
 * To add a product: copy an entry, give it a unique id, slug and SKUs,
 * put its images in public/images/products/<slug>/, and set status "active".
 */

const img = (slug: string, file: string, alt: string): ProductImage => ({
  src: `/images/products/${slug}/${file}.svg`,
  alt,
  width: 1200,
  height: 1500,
});

export const products: Product[] = [
  // ---------------------------------------------------------------- Kitchen
  {
    id: "p-001",
    slug: "stoneware-mug-set",
    name: "Stoneware Mug, Set of Two",
    collection: "kitchen-dining",
    status: "active",
    sample: true,
    summary: "A pair of 12 oz glazed stoneware mugs with an exposed clay base.",
    description: [
      "Two everyday mugs with a straight, slightly weighted body and a handle sized for a full grip. The glaze stops short of the base, leaving a band of bare stoneware that keeps the mugs steady on the counter.",
      "Because each piece is glazed and fired in small batches, expect slight variation in tone and glaze pooling from one mug to the next.",
    ],
    features: [
      "Holds 12 fl oz filled to the rim",
      "Unglazed foot ring sits flat on most surfaces",
      "Wide handle with room for three fingers",
      "Sold as a matching pair",
    ],
    specifications: [
      { label: "Material", value: "Glazed stoneware" },
      { label: "Capacity", value: "12 fl oz (355 ml)" },
      { label: "Dimensions", value: "3.5 in diameter × 4 in tall, each" },
      { label: "Weight", value: "approx. 13 oz each" },
    ],
    included: ["2 stoneware mugs in the selected color"],
    care: ["Hand washing recommended to preserve the glaze finish.", "Avoid sudden temperature changes, such as pouring boiling water into a cold mug."],
    returnable: true,
    options: [{ name: "Color", values: ["Sand", "Slate", "Moss"] }],
    variants: [
      { sku: "CH-KD-MUG2-SND", options: { Color: "Sand" }, priceCents: 3400, inventory: 40, imageIndex: 0 },
      { sku: "CH-KD-MUG2-SLT", options: { Color: "Slate" }, priceCents: 3400, inventory: 32, imageIndex: 1 },
      { sku: "CH-KD-MUG2-MOS", options: { Color: "Moss" }, priceCents: 3400, inventory: 0, imageIndex: 2 },
    ],
    images: [
      img("stoneware-mug-set", "sand", "Two sand-colored stoneware mugs"),
      img("stoneware-mug-set", "slate", "Two slate-gray stoneware mugs"),
      img("stoneware-mug-set", "moss", "Two moss-green stoneware mugs"),
      img("stoneware-mug-set", "detail", "Close-up of the mug handle and glaze line"),
    ],
    weight: { value: 2.2, unit: "lb" },
    dimensions: { length: 9, width: 6, height: 5, unit: "in" },
    tags: ["mug", "coffee", "tea", "stoneware", "ceramic", "kitchen"],
    merchandising: { featured: true },
  },
  {
    id: "p-002",
    slug: "glass-pour-over-set",
    name: "Glass Pour-Over Coffee Set",
    collection: "kitchen-dining",
    status: "active",
    sample: true,
    summary: "A 20 oz borosilicate glass carafe with matching dripper and a reusable mesh filter.",
    description: [
      "A two-piece brewer for making two to three cups at a time. The cone-shaped dripper sits directly on the carafe, and the reusable stainless steel mesh filter means you don't need paper filters on hand.",
      "The carafe has a wood collar with a cord tie so it can be handled while full. The collar is removable for washing the glass.",
    ],
    features: [
      "Brews up to 20 fl oz",
      "Reusable stainless steel mesh filter included",
      "Removable wood collar for handling",
      "Measurement marks on the carafe at 10 and 20 fl oz",
    ],
    specifications: [
      { label: "Carafe material", value: "Borosilicate glass" },
      { label: "Collar", value: "Beech wood with cotton cord" },
      { label: "Filter", value: "Stainless steel mesh" },
      { label: "Capacity", value: "20 fl oz (600 ml)" },
      { label: "Assembled height", value: "9.5 in" },
    ],
    included: ["Glass carafe", "Glass dripper", "Stainless steel mesh filter", "Wood collar with cord"],
    care: ["Hand wash only. Remove the wood collar before washing.", "Rinse the mesh filter immediately after use; a soft brush clears fine grounds.", "Do not place the carafe directly on a stovetop burner."],
    shippingNote: "Glass items are packed with molded inserts. Please inspect the carafe on arrival and report any damage promptly.",
    returnable: true,
    options: [],
    variants: [{ sku: "CH-KD-POUR-20", options: {}, priceCents: 4800, inventory: 25 }],
    images: [
      img("glass-pour-over-set", "1", "Glass pour-over carafe and dripper"),
      img("glass-pour-over-set", "2", "Pour-over set next to a stoneware mug"),
      img("glass-pour-over-set", "detail", "Close-up of the dripper and wood collar"),
    ],
    weight: { value: 2.6, unit: "lb" },
    dimensions: { length: 8, width: 8, height: 11, unit: "in" },
    tags: ["coffee", "pour over", "carafe", "glass", "brewer", "kitchen"],
    merchandising: { featured: true },
  },
  {
    id: "p-003",
    slug: "acacia-cutting-board",
    name: "Acacia Wood Cutting Board",
    collection: "kitchen-dining",
    status: "active",
    sample: true,
    summary: "An edge-grain acacia board with a cut-out handle, in two sizes.",
    description: [
      "A solid acacia cutting board made from edge-grain strips, finished with food-grade mineral oil. The cut-out handle makes it easy to lift, hang, or carry to the table for serving.",
      "Acacia is a hardwood with visible grain and color variation, so no two boards look exactly alike.",
    ],
    features: [
      "Edge-grain construction",
      "Cut-out handle for carrying and hanging",
      "Eased edges and rounded corners",
      "Two sizes",
    ],
    specifications: [
      { label: "Material", value: "Acacia wood" },
      { label: "Finish", value: "Food-grade mineral oil" },
      { label: "Medium", value: "14 × 10 × 0.75 in" },
      { label: "Large", value: "18 × 12 × 0.75 in" },
    ],
    included: ["1 cutting board in the selected size"],
    care: ["Hand wash with mild soap and dry upright. Do not soak or put in the dishwasher.", "Re-oil with food-grade mineral oil when the surface looks dry."],
    returnable: true,
    options: [{ name: "Size", values: ["Medium", "Large"] }],
    variants: [
      { sku: "CH-KD-BRD-MD", options: { Size: "Medium" }, priceCents: 3800, inventory: 30 },
      { sku: "CH-KD-BRD-LG", options: { Size: "Large" }, priceCents: 5200, inventory: 18 },
    ],
    images: [
      img("acacia-cutting-board", "1", "Acacia cutting board standing upright"),
      img("acacia-cutting-board", "2", "Medium and large acacia cutting boards side by side"),
      img("acacia-cutting-board", "detail", "Close-up of the acacia grain and handle"),
    ],
    weight: { value: 3.4, unit: "lb" },
    dimensions: { length: 19, width: 13, height: 2, unit: "in" },
    tags: ["cutting board", "wood", "acacia", "serving", "kitchen"],
    merchandising: { featured: true },
  },

  // ---------------------------------------------------------------- Home
  {
    id: "p-004",
    slug: "waffle-knit-throw",
    name: "Waffle Knit Cotton Throw",
    collection: "home-living",
    status: "active",
    sample: true,
    summary: "A 50 × 60 in cotton throw with a textured waffle weave.",
    description: [
      "A mid-weight throw woven from cotton in a deep waffle texture. It's sized for a sofa or the foot of a bed and is light enough to use most of the year.",
      "The edges are finished with a narrow hem rather than fringe, so it folds flat and holds its shape after washing.",
    ],
    features: ["Deep waffle weave", "Hemmed edges, no fringe", "Machine washable", "Three colors"],
    specifications: [
      { label: "Material", value: "100% cotton" },
      { label: "Dimensions", value: "50 × 60 in" },
      { label: "Weight", value: "approx. 2 lb" },
    ],
    included: ["1 throw in the selected color"],
    care: ["Machine wash cold on a gentle cycle with like colors.", "Tumble dry low or line dry. Some shrinkage (around 3–5%) is normal for cotton."],
    returnable: true,
    options: [{ name: "Color", values: ["Oatmeal", "Charcoal", "Sage"] }],
    variants: [
      { sku: "CH-HL-THR-OAT", options: { Color: "Oatmeal" }, priceCents: 7800, inventory: 22, imageIndex: 0 },
      { sku: "CH-HL-THR-CHR", options: { Color: "Charcoal" }, priceCents: 7800, inventory: 15, imageIndex: 1 },
      { sku: "CH-HL-THR-SAG", options: { Color: "Sage" }, priceCents: 7800, inventory: 12, imageIndex: 2 },
    ],
    images: [
      img("waffle-knit-throw", "oatmeal", "Folded oatmeal waffle knit throw"),
      img("waffle-knit-throw", "charcoal", "Folded charcoal waffle knit throw"),
      img("waffle-knit-throw", "sage", "Folded sage waffle knit throw"),
      img("waffle-knit-throw", "detail", "Close-up of the waffle weave texture"),
    ],
    weight: { value: 2.4, unit: "lb" },
    dimensions: { length: 14, width: 12, height: 4, unit: "in" },
    tags: ["throw", "blanket", "cotton", "textiles", "living room", "bedroom"],
    merchandising: { featured: true },
  },
  {
    id: "p-005",
    slug: "linen-blend-pillow-cover",
    name: "Linen Blend Pillow Cover",
    collection: "home-living",
    status: "active",
    sample: true,
    summary: "A linen-cotton pillow cover with a hidden zipper. Insert sold separately.",
    description: [
      "A simple pillow cover in a linen and cotton blend with a soft, slightly irregular texture. A zipper along the bottom seam is hidden under a fabric flap.",
      "This listing is for the cover only. It fits a standard insert of the same size; for a fuller look, many people size the insert up by 2 inches.",
    ],
    features: ["Hidden zipper closure", "Knife-edge seams", "Two sizes, two colors", "Insert not included"],
    specifications: [
      { label: "Material", value: "55% linen, 45% cotton" },
      { label: "18 × 18 in", value: "Fits an 18 or 20 in insert" },
      { label: "20 × 20 in", value: "Fits a 20 or 22 in insert" },
      { label: "Closure", value: "Concealed zipper" },
    ],
    included: ["1 pillow cover (insert not included)"],
    care: ["Turn inside out and machine wash cold on gentle.", "Line dry. Warm iron while slightly damp if desired."],
    returnable: true,
    options: [
      { name: "Color", values: ["Natural", "Clay"] },
      { name: "Size", values: ["18 × 18 in", "20 × 20 in"] },
    ],
    variants: [
      { sku: "CH-HL-PIL-NAT-18", options: { Color: "Natural", Size: "18 × 18 in" }, priceCents: 3200, inventory: 26, imageIndex: 0 },
      { sku: "CH-HL-PIL-NAT-20", options: { Color: "Natural", Size: "20 × 20 in" }, priceCents: 3600, inventory: 20, imageIndex: 0 },
      { sku: "CH-HL-PIL-CLY-18", options: { Color: "Clay", Size: "18 × 18 in" }, priceCents: 3200, inventory: 18, imageIndex: 1 },
      { sku: "CH-HL-PIL-CLY-20", options: { Color: "Clay", Size: "20 × 20 in" }, priceCents: 3600, inventory: 14, imageIndex: 1 },
    ],
    images: [
      img("linen-blend-pillow-cover", "natural", "Natural linen blend pillow cover"),
      img("linen-blend-pillow-cover", "clay", "Clay-colored linen blend pillow cover"),
      img("linen-blend-pillow-cover", "detail", "Close-up of the linen weave and seam"),
    ],
    weight: { value: 8, unit: "oz" },
    dimensions: { length: 10, width: 8, height: 1, unit: "in" },
    tags: ["pillow", "cushion", "linen", "textiles", "living room"],
    merchandising: { essentials: true },
  },
  {
    id: "p-006",
    slug: "ceramic-table-planter",
    name: "Ceramic Table Planter with Saucer",
    collection: "home-living",
    status: "active",
    sample: true,
    summary: "A matte ceramic planter with a drainage hole and matching saucer. Plant not included.",
    description: [
      "A tapered planter with a matte exterior glaze and a fitted saucer to catch runoff. The drainage hole helps prevent water from collecting at the roots.",
      "Choose the small size for herbs and small succulents, or the medium for most 6 in nursery pots.",
    ],
    features: ["Drainage hole with matching saucer", "Matte exterior glaze", "Two sizes", "Plant and soil not included"],
    specifications: [
      { label: "Material", value: "Glazed ceramic" },
      { label: "Small", value: "5 in diameter × 5 in tall; fits a 4 in nursery pot" },
      { label: "Medium", value: "7 in diameter × 7 in tall; fits a 6 in nursery pot" },
    ],
    included: ["1 planter", "1 matching saucer"],
    care: ["Wipe clean with a damp cloth.", "For outdoor use, bring indoors before freezing temperatures."],
    shippingNote: "Ceramics are packed individually with protective inserts. Please inspect on arrival and report any damage promptly.",
    returnable: true,
    options: [
      { name: "Color", values: ["White", "Charcoal"] },
      { name: "Size", values: ["Small", "Medium"] },
    ],
    variants: [
      { sku: "CH-HL-PLN-WHT-S", options: { Color: "White", Size: "Small" }, priceCents: 2800, inventory: 24, imageIndex: 0 },
      { sku: "CH-HL-PLN-WHT-M", options: { Color: "White", Size: "Medium" }, priceCents: 3800, inventory: 16, imageIndex: 0 },
      { sku: "CH-HL-PLN-CHR-S", options: { Color: "Charcoal", Size: "Small" }, priceCents: 2800, inventory: 20, imageIndex: 1 },
      { sku: "CH-HL-PLN-CHR-M", options: { Color: "Charcoal", Size: "Medium" }, priceCents: 3800, inventory: 0, imageIndex: 1 },
    ],
    images: [
      img("ceramic-table-planter", "white", "White ceramic planter with saucer"),
      img("ceramic-table-planter", "charcoal", "Charcoal ceramic planter with saucer"),
      img("ceramic-table-planter", "detail", "Close-up of the planter rim and glaze"),
    ],
    weight: { value: 2.8, unit: "lb" },
    dimensions: { length: 10, width: 10, height: 10, unit: "in" },
    tags: ["planter", "pot", "ceramic", "plants", "decor"],
    merchandising: { featured: true },
  },

  // ---------------------------------------------------------------- Desk
  {
    id: "p-007",
    slug: "wool-felt-desk-pad",
    name: "Wool Felt Desk Pad",
    collection: "desk-office",
    status: "active",
    sample: true,
    summary: "A wool-blend felt desk mat with a natural cork underside, in two sizes.",
    description: [
      "A desk mat with a wool-blend felt top and a natural cork base. It gives your keyboard and mouse a consistent surface and helps protect the desk underneath from scratches.",
      "The felt is dense and cut cleanly at the edges. The cork side grips the desk without adhesive.",
    ],
    features: ["Wool-blend felt top", "Cork underside, no adhesive", "Works with optical mice", "Two sizes, two colors"],
    specifications: [
      { label: "Top", value: "Wool-blend felt (70% wool, 30% polyester)" },
      { label: "Base", value: "Natural cork" },
      { label: "Thickness", value: "4 mm" },
      { label: "Standard", value: "24 × 12 in" },
      { label: "Large", value: "36 × 16 in" },
    ],
    included: ["1 desk pad, shipped rolled"],
    care: ["Spot clean with a damp cloth and mild soap. Do not machine wash.", "Lay flat for a few hours after unrolling."],
    returnable: true,
    options: [
      { name: "Color", values: ["Charcoal", "Gray"] },
      { name: "Size", values: ["Standard", "Large"] },
    ],
    variants: [
      { sku: "CH-DO-PAD-CHR-STD", options: { Color: "Charcoal", Size: "Standard" }, priceCents: 4400, inventory: 30, imageIndex: 0 },
      { sku: "CH-DO-PAD-CHR-LG", options: { Color: "Charcoal", Size: "Large" }, priceCents: 5800, inventory: 22, imageIndex: 0 },
      { sku: "CH-DO-PAD-GRY-STD", options: { Color: "Gray", Size: "Standard" }, priceCents: 4400, inventory: 18, imageIndex: 1 },
      { sku: "CH-DO-PAD-GRY-LG", options: { Color: "Gray", Size: "Large" }, priceCents: 5800, inventory: 12, imageIndex: 1 },
    ],
    images: [
      img("wool-felt-desk-pad", "charcoal", "Charcoal felt desk pad on a desk"),
      img("wool-felt-desk-pad", "gray", "Gray felt desk pad on a desk"),
      img("wool-felt-desk-pad", "detail", "Close-up of the felt surface and edge"),
    ],
    weight: { value: 1.6, unit: "lb" },
    dimensions: { length: 18, width: 4, height: 4, unit: "in" },
    tags: ["desk mat", "desk pad", "felt", "office", "workspace"],
    merchandising: { featured: true },
  },
  {
    id: "p-008",
    slug: "walnut-monitor-stand",
    name: "Walnut Monitor Stand",
    collection: "desk-office",
    status: "active",
    sample: true,
    summary: "A walnut-veneer monitor riser on powder-coated steel legs.",
    description: [
      "A low, wide riser that lifts a monitor or laptop about 4 inches and leaves space underneath for a keyboard or notebooks when you're done for the day.",
      "The shelf is walnut-veneered plywood with a clear matte finish. The steel legs attach with the included hardware in a few minutes.",
    ],
    features: ["Raises the screen approx. 4 in", "Storage space underneath", "Felt pads on each foot", "Tools and hardware included"],
    specifications: [
      { label: "Shelf", value: "Walnut-veneered plywood, matte lacquer" },
      { label: "Legs", value: "Powder-coated steel, black" },
      { label: "Dimensions", value: "24 × 9 × 4.25 in" },
      { label: "Clearance underneath", value: "3.5 in" },
      { label: "Recommended max load", value: "30 lb, evenly distributed" },
    ],
    included: ["Shelf", "2 steel legs", "4 screws", "Hex key", "4 adhesive felt pads"],
    care: ["Wipe with a soft, dry or slightly damp cloth. Avoid standing water on the wood."],
    returnable: true,
    options: [],
    variants: [{ sku: "CH-DO-STND-WAL", options: {}, priceCents: 8900, inventory: 14 }],
    images: [
      img("walnut-monitor-stand", "1", "Walnut monitor stand with black steel legs"),
      img("walnut-monitor-stand", "2", "Monitor stand with a notebook beside it"),
      img("walnut-monitor-stand", "detail", "Close-up of the walnut shelf edge"),
    ],
    weight: { value: 7.5, unit: "lb" },
    dimensions: { length: 27, width: 12, height: 4, unit: "in" },
    tags: ["monitor stand", "riser", "walnut", "desk", "office"],
    merchandising: { featured: true },
  },
  {
    id: "p-009",
    slug: "hardcover-dot-grid-notebook",
    name: "Hardcover Dot-Grid Notebook, A5",
    collection: "desk-office",
    status: "active",
    sample: true,
    summary: "An A5 notebook with 192 dot-grid pages, lay-flat binding and an elastic closure.",
    description: [
      "A hardcover notebook with a linen-textured cover, 100 gsm paper and a sewn binding that opens flat on the desk. The light dot grid works for writing, lists and simple sketches.",
      "It includes an elastic closure, a ribbon bookmark and an expandable pocket inside the back cover.",
    ],
    features: ["192 numbered dot-grid pages", "Lay-flat sewn binding", "Elastic closure and ribbon bookmark", "Back-cover pocket"],
    specifications: [
      { label: "Size", value: "A5 (5.8 × 8.3 in)" },
      { label: "Pages", value: "192 (96 sheets)" },
      { label: "Paper", value: "100 gsm, ivory" },
      { label: "Ruling", value: "5 mm dot grid" },
    ],
    included: ["1 notebook in the selected color"],
    returnable: true,
    options: [{ name: "Color", values: ["Navy", "Forest", "Black"] }],
    variants: [
      { sku: "CH-DO-NB-NVY", options: { Color: "Navy" }, priceCents: 2200, inventory: 60, imageIndex: 0 },
      { sku: "CH-DO-NB-FOR", options: { Color: "Forest" }, priceCents: 2200, inventory: 45, imageIndex: 1 },
      { sku: "CH-DO-NB-BLK", options: { Color: "Black" }, priceCents: 2200, inventory: 50, imageIndex: 2 },
    ],
    images: [
      img("hardcover-dot-grid-notebook", "navy", "Navy hardcover notebook"),
      img("hardcover-dot-grid-notebook", "forest", "Forest green hardcover notebook"),
      img("hardcover-dot-grid-notebook", "black", "Black hardcover notebook"),
      img("hardcover-dot-grid-notebook", "detail", "Close-up of the notebook cover and elastic"),
    ],
    weight: { value: 12, unit: "oz" },
    dimensions: { length: 9, width: 6.5, height: 1, unit: "in" },
    tags: ["notebook", "journal", "paper", "stationery", "office"],
    merchandising: { essentials: true },
  },

  // ---------------------------------------------------------------- Travel
  {
    id: "p-010",
    slug: "waxed-canvas-weekender",
    name: "Waxed Canvas Weekender Bag",
    collection: "travel-carry",
    status: "active",
    sample: true,
    summary: "A roughly 40-liter waxed cotton canvas duffel with leather handles.",
    description: [
      "A structured duffel sized for two or three nights away. The body is heavyweight cotton canvas treated with wax, with leather handles and end panels and a full-length metal zipper.",
      "Waxed canvas creases and marks with use, and the finish changes over time. That's expected and part of the material's character. An adjustable shoulder strap clips on when you need your hands free.",
    ],
    features: [
      "Approx. 40 L capacity",
      "Full-length metal zipper",
      "Interior zip pocket and two slip pockets",
      "Detachable, adjustable shoulder strap",
    ],
    specifications: [
      { label: "Body", value: "Waxed cotton canvas, 18 oz" },
      { label: "Trim and handles", value: "Leather" },
      { label: "Lining", value: "Cotton twill" },
      { label: "Dimensions", value: "22 × 12 × 10 in" },
      { label: "Weight", value: "approx. 3.4 lb" },
    ],
    included: ["Weekender bag", "Detachable shoulder strap"],
    care: ["Brush off dirt once dry and spot clean with cold water. Do not machine wash or dry clean.", "Can be re-waxed with a fabric wax bar if the finish wears thin."],
    returnable: true,
    options: [{ name: "Color", values: ["Olive", "Navy"] }],
    variants: [
      { sku: "CH-TC-WKD-OLV", options: { Color: "Olive" }, priceCents: 14500, inventory: 10, imageIndex: 0 },
      { sku: "CH-TC-WKD-NVY", options: { Color: "Navy" }, priceCents: 14500, inventory: 8, imageIndex: 1 },
    ],
    images: [
      img("waxed-canvas-weekender", "olive", "Olive waxed canvas weekender bag"),
      img("waxed-canvas-weekender", "navy", "Navy waxed canvas weekender bag"),
      img("waxed-canvas-weekender", "detail", "Close-up of the leather handles and zipper"),
    ],
    weight: { value: 4.2, unit: "lb" },
    dimensions: { length: 23, width: 13, height: 6, unit: "in" },
    tags: ["bag", "duffel", "weekender", "travel", "canvas", "leather"],
    merchandising: { featured: true },
  },
  {
    id: "p-011",
    slug: "packing-cube-set",
    name: "Packing Cube Set of Three",
    collection: "travel-carry",
    status: "active",
    sample: true,
    summary: "Three nesting ripstop nylon packing cubes with mesh tops.",
    description: [
      "Three zippered cubes in small, medium and large that keep clothes sorted in a suitcase or duffel. Mesh panels let you see what's inside without opening them.",
      "Each cube has a fabric pull loop at one end, and the set nests together for storage when you're home.",
    ],
    features: ["Small, medium and large sizes", "Mesh top panels", "Two-way zippers", "Nest together for storage"],
    specifications: [
      { label: "Material", value: "Ripstop nylon with polyester mesh" },
      { label: "Large", value: "16 × 12 × 4 in" },
      { label: "Medium", value: "13 × 10 × 3.5 in" },
      { label: "Small", value: "10 × 7 × 3 in" },
    ],
    included: ["3 packing cubes (S, M, L)"],
    care: ["Hand wash in cold water and air dry."],
    returnable: true,
    options: [{ name: "Color", values: ["Gray", "Navy"] }],
    variants: [
      { sku: "CH-TC-CUBE3-GRY", options: { Color: "Gray" }, priceCents: 3900, inventory: 35, imageIndex: 0 },
      { sku: "CH-TC-CUBE3-NVY", options: { Color: "Navy" }, priceCents: 3900, inventory: 28, imageIndex: 1 },
    ],
    images: [
      img("packing-cube-set", "gray", "Stack of three gray packing cubes"),
      img("packing-cube-set", "navy", "Stack of three navy packing cubes"),
      img("packing-cube-set", "detail", "Close-up of the mesh panel and zipper"),
    ],
    weight: { value: 14, unit: "oz" },
    dimensions: { length: 17, width: 13, height: 3, unit: "in" },
    tags: ["packing cubes", "travel", "organizer", "luggage"],
    merchandising: { essentials: true },
  },
  {
    id: "p-012",
    slug: "canvas-zip-pouch",
    name: "Canvas Zip Pouch",
    collection: "travel-carry",
    status: "active",
    sample: true,
    summary: "A flat cotton canvas pouch with a metal zipper and leather pull.",
    description: [
      "A flat, lined pouch for cables, pens, toiletries or travel documents. It's sized to fit inside a tote or weekender without taking up much room.",
      "The heavy cotton canvas has a slightly stiff hand at first and softens with use.",
    ],
    features: ["Metal zipper with leather pull", "Cotton twill lining", "Fits passports, chargers and cables", "Two colors"],
    specifications: [
      { label: "Exterior", value: "Cotton canvas, 16 oz" },
      { label: "Lining", value: "Cotton twill" },
      { label: "Dimensions", value: "10 × 6.5 in" },
    ],
    included: ["1 zip pouch"],
    care: ["Spot clean with cold water and mild soap. Air dry."],
    returnable: true,
    options: [{ name: "Color", values: ["Natural", "Black"] }],
    variants: [
      { sku: "CH-TC-POUCH-NAT", options: { Color: "Natural" }, priceCents: 2400, inventory: 40, imageIndex: 0 },
      { sku: "CH-TC-POUCH-BLK", options: { Color: "Black" }, priceCents: 2400, inventory: 36, imageIndex: 1 },
    ],
    images: [
      img("canvas-zip-pouch", "natural", "Natural canvas zip pouch"),
      img("canvas-zip-pouch", "black", "Black canvas zip pouch"),
      img("canvas-zip-pouch", "detail", "Close-up of the zipper and leather pull"),
    ],
    weight: { value: 5, unit: "oz" },
    dimensions: { length: 11, width: 8, height: 1, unit: "in" },
    tags: ["pouch", "case", "canvas", "travel", "organizer"],
    merchandising: { essentials: true },
  },
];
