import type { Product } from "./types";

/*
 * PLANNED INITIAL CATALOG
 *
 * These entries contain only the information supplied by the business:
 * name, collection, planned price, SKU prefix and positioning. Every other
 * product fact is listed in `pendingData` and must be supplied from the
 * actual product / supplier documentation before the product is activated.
 *
 * Do not add materials, dimensions, capacities, specifications, inventory,
 * SKUs, certifications or photography that have not been verified.
 *
 * To activate a product: fill in the verified facts, add variants with full
 * SKUs (starting with skuPrefix) and real inventory, add photography, clear
 * pendingData and set status "active". `npm run check:launch` and the test
 * suite reject an "active" product that is missing required data.
 */

/** Facts every product needs before it can be sold. */
const commonPending = [
  "full SKU(s) and verified inventory per variant",
  "packaged shipping weight and package dimensions",
  "return eligibility (returnable or final sale)",
  "verified product photography",
];

export const products: Product[] = [
  // ---------------------------------------------------------------- Kitchen & Dining
  {
    id: "p-001",
    slug: "digital-kitchen-scale",
    name: "Crestmont Digital Kitchen Scale",
    collection: "kitchen-dining",
    status: "coming_soon",
    skuPrefix: "CH-KIT-SCALE",
    priceCents: 2999,
    summary: "A compact digital kitchen scale for everyday food preparation and portion measurement.",
    options: [],
    variants: [],
    images: [],
    tags: ["kitchen scale", "scale", "digital", "kitchen", "cooking", "baking", "portion"],
    pendingData: ["measurement range", "accuracy", "product dimensions", "materials", "battery type", "included items", ...commonPending],
  },
  {
    id: "p-002",
    slug: "glass-food-storage-set",
    name: "Crestmont Glass Food Storage Set",
    collection: "kitchen-dining",
    status: "coming_soon",
    skuPrefix: "CH-KIT-STORE",
    priceCents: 4499,
    summary: "A coordinated set of food-storage containers for the refrigerator, pantry and meal preparation.",
    options: [],
    variants: [],
    images: [],
    tags: ["food storage", "containers", "glass", "meal prep", "kitchen", "pantry"],
    pendingData: [
      "number of containers",
      "container capacities",
      "container materials",
      "lid materials",
      "dishwasher, freezer and microwave compatibility",
      "package contents",
      "product dimensions",
      ...commonPending,
    ],
  },
  {
    id: "p-003",
    slug: "insulated-travel-tumbler",
    name: "Crestmont Insulated Travel Tumbler",
    collection: "kitchen-dining",
    status: "coming_soon",
    skuPrefix: "CH-KIT-TUMBLER",
    priceCents: 3499,
    summary: "An insulated tumbler for taking drinks with you through the day.",
    options: [],
    variants: [],
    images: [],
    tags: ["tumbler", "travel mug", "insulated", "drinkware", "kitchen", "travel"],
    pendingData: [
      "capacity",
      "materials",
      "insulation construction",
      "lid design",
      "product dimensions",
      "care instructions",
      "available colors confirmed by inventory (planned: Black, White, Navy)",
      ...commonPending,
    ],
  },

  // ---------------------------------------------------------------- Home Organization
  {
    id: "p-004",
    slug: "modular-drawer-organizer",
    name: "Crestmont Modular Drawer Organizer",
    collection: "home-organization",
    status: "coming_soon",
    skuPrefix: "CH-ORG-DRAWER",
    priceCents: 2799,
    summary: "A modular organizer system for commonly used household drawers.",
    options: [],
    variants: [],
    images: [],
    tags: ["drawer organizer", "organizer", "modular", "storage", "organization", "kitchen drawer"],
    pendingData: ["number of pieces", "individual piece dimensions", "materials", "available colors", "package contents", ...commonPending],
  },
  {
    id: "p-005",
    slug: "under-sink-organizer",
    name: "Crestmont Under-Sink Organizer",
    collection: "home-organization",
    status: "coming_soon",
    skuPrefix: "CH-ORG-SINK",
    priceCents: 3999,
    summary: "A compact storage unit for making better use of under-sink cabinet space.",
    options: [],
    variants: [],
    images: [],
    tags: ["under sink", "organizer", "cabinet", "storage", "organization", "bathroom", "kitchen"],
    pendingData: ["product dimensions", "materials", "weight capacity (only if verified)", "assembly requirements", "package contents", ...commonPending],
  },
  {
    id: "p-006",
    slug: "foldable-storage-bins",
    name: "Crestmont Foldable Storage Bins",
    collection: "home-organization",
    status: "coming_soon",
    skuPrefix: "CH-ORG-BIN",
    priceCents: 3699,
    summary: "Foldable storage bins for flexible, everyday organization around the home.",
    options: [],
    variants: [],
    images: [],
    tags: ["storage bins", "bins", "foldable", "baskets", "storage", "organization", "closet", "shelf"],
    pendingData: ["quantity per set", "bin dimensions", "materials", "closure design", "available colors", "product weight", ...commonPending],
  },

  // ---------------------------------------------------------------- Home Comfort
  {
    id: "p-007",
    slug: "bedside-table-lamp",
    name: "Crestmont Bedside Table Lamp",
    collection: "home-comfort",
    status: "coming_soon",
    skuPrefix: "CH-HOME-LAMP",
    priceCents: 4299,
    summary: "A compact table lamp for bedrooms, desks and small living spaces.",
    options: [],
    variants: [],
    images: [],
    tags: ["lamp", "table lamp", "bedside", "lighting", "bedroom", "desk"],
    pendingData: [
      "voltage",
      "plug type",
      "bulb / light source (and whether included)",
      "power rating",
      "product dimensions",
      "materials",
      "controls",
      "electrical certifications, with documentation (only if applicable)",
      "included items",
      ...commonPending,
    ],
  },
  {
    id: "p-008",
    slug: "textured-throw-blanket",
    name: "Crestmont Textured Throw Blanket",
    collection: "home-comfort",
    status: "coming_soon",
    skuPrefix: "CH-HOME-THROW",
    priceCents: 4999,
    summary: "A textured throw blanket for sofas, chairs and beds.",
    options: [],
    variants: [],
    images: [],
    tags: ["throw", "blanket", "textiles", "living room", "bedroom", "sofa"],
    pendingData: [
      "dimensions",
      "textile fiber composition",
      "care instructions",
      "available colors",
      "country of origin (required on textile labeling)",
      ...commonPending,
    ],
  },
  {
    id: "p-009",
    slug: "decorative-cushion-set",
    name: "Crestmont Decorative Cushion Set",
    collection: "home-comfort",
    status: "coming_soon",
    skuPrefix: "CH-HOME-CUSHION",
    priceCents: 3999,
    summary: "A coordinated decorative cushion set for sofas, chairs and bedrooms.",
    options: [],
    variants: [],
    images: [],
    tags: ["cushions", "pillows", "throw pillows", "decor", "living room", "bedroom", "sofa"],
    pendingData: [
      "number of cushions",
      "cushion dimensions",
      "cover material",
      "filling material",
      "removable cover (yes / no)",
      "care instructions",
      ...commonPending,
    ],
  },

  // ---------------------------------------------------------------- Travel & Everyday Essentials
  {
    id: "p-010",
    slug: "packing-cube-set",
    name: "Crestmont Packing Cube Set",
    collection: "travel-everyday-essentials",
    status: "coming_soon",
    skuPrefix: "CH-TRV-CUBE",
    priceCents: 3299,
    summary: "A multi-piece packing organizer set for luggage and everyday travel.",
    options: [],
    variants: [],
    images: [],
    tags: ["packing cubes", "travel", "luggage", "organizer", "suitcase"],
    pendingData: ["number of pieces", "individual piece dimensions", "materials", "closures", "available colors", ...commonPending],
  },
  {
    id: "p-011",
    slug: "tech-organizer-pouch",
    name: "Crestmont Tech Organizer Pouch",
    collection: "travel-everyday-essentials",
    status: "coming_soon",
    skuPrefix: "CH-TRV-TECH",
    priceCents: 2899,
    summary: "A compact organizer for cables and small everyday technology accessories.",
    options: [],
    variants: [],
    images: [],
    tags: ["tech organizer", "cable organizer", "pouch", "travel", "chargers", "electronics"],
    pendingData: ["product dimensions", "materials", "compartment configuration", "closure", "available colors", ...commonPending],
  },
  {
    id: "p-012",
    slug: "travel-toiletry-organizer",
    name: "Crestmont Travel Toiletry Organizer",
    collection: "travel-everyday-essentials",
    status: "coming_soon",
    skuPrefix: "CH-TRV-TOILETRY",
    priceCents: 3199,
    summary: "A travel organizer for toiletries and personal-care essentials.",
    options: [],
    variants: [],
    images: [],
    tags: ["toiletry bag", "toiletry organizer", "travel", "personal care", "bathroom"],
    pendingData: ["product dimensions", "materials", "compartments", "hanging mechanism (if applicable)", "available colors", ...commonPending],
  },
];
