"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Eye, RotateCcw, Trash2, Download, Loader2 } from "lucide-react";

import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogTrigger,
} from "@/components/ui/dialog";
import { designStatusMeta, designStatusLabel } from "@/config/generation";
import { retryDesignAction, deleteDesignAction } from "@/app/actions/generation";
import type { Design } from "@/types/supabase";

function formatDate(value: string) {
  return new Date(value).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export function DesignCard({
  design,
  projectName,
}: {
  design: Design;
  /** Shown in the detail dialog on cross-project views like /dashboard/designs. */
  projectName?: string;
}) {
  const router = useRouter();
  const [open, setOpen] = React.useState(false);
  const [isRetrying, setIsRetrying] = React.useState(false);
  const [isDeleting, setIsDeleting] = React.useState(false);
  const [actionError, setActionError] = React.useState<string | null>(null);
  const statusMeta = designStatusMeta[design.status as keyof typeof designStatusMeta];
  const isFailed = design.status === "failed";

  async function handleRetry() {
    setIsRetrying(true);
    setActionError(null);
    const result = await retryDesignAction({ id: design.id });
    setIsRetrying(false);
    if (!result.ok) {
      setActionError(result.error);
    } else {
      router.refresh();
    }
  }

  async function handleDelete() {
    setIsDeleting(true);
    setActionError(null);
    const result = await deleteDesignAction({ id: design.id });
    setIsDeleting(false);
    if (!result.ok) {
      setActionError(result.error);
    } else {
      setOpen(false);
      router.refresh();
    }
  }

  return (
    <Card className="flex flex-col overflow-hidden">
      <div className="relative aspect-square bg-muted/50">
        {design.image_url ? (
          // eslint-disable-next-line @next/next/no-img-element -- mock preview is a self-contained data: URI generated by MockImageProvider, not a remote asset
          <img src={design.image_url} alt={design.title} className="size-full object-contain" />
        ) : (
          <div className="flex size-full items-center justify-center text-muted-foreground">
            {design.status === "generating" ? (
              <Loader2 className="size-6 animate-spin" aria-label="Generating" />
            ) : (
              <span className="text-xs">No preview</span>
            )}
          </div>
        )}
        <Badge variant={statusMeta?.badgeVariant ?? "outline"} className="absolute top-2 left-2">
          {designStatusLabel(design.status)}
        </Badge>
        <Badge variant="outline" className="absolute top-2 right-2 bg-card/90">
          #{design.variation_index + 1}
        </Badge>
      </div>
      <CardContent className="flex flex-1 flex-col gap-2 p-3">
        <p className="line-clamp-1 text-sm font-medium">{design.title}</p>
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>Variation #{design.variation_index + 1}</span>
          <span>{formatDate(design.created_at)}</span>
        </div>
        {actionError && <p className="text-xs text-destructive">{actionError}</p>}
        <div className="mt-auto flex flex-wrap gap-1.5 pt-1">
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button type="button" variant="outline" size="sm">
                <Eye className="size-3.5" />
                View
              </Button>
            </DialogTrigger>
            <DialogContent className="max-h-[90vh] max-w-lg overflow-y-auto">
              <DialogHeader>
                <DialogTitle>{design.title}</DialogTitle>
                <DialogDescription>
                  Development Preview — mock generation, not a real AI-generated design.
                </DialogDescription>
              </DialogHeader>
              <div className="mt-2 flex flex-col gap-4">
                <div className="overflow-hidden rounded-xl border border-border bg-muted/50">
                  {design.image_url ? (
                    // eslint-disable-next-line @next/next/no-img-element -- see note above
                    <img src={design.image_url} alt={design.title} className="w-full" />
                  ) : (
                    <div className="flex aspect-square items-center justify-center text-sm text-muted-foreground">
                      No preview available
                    </div>
                  )}
                </div>

                <dl className="grid grid-cols-2 gap-3 text-sm">
                  <div>
                    <dt className="text-xs text-muted-foreground">Status</dt>
                    <dd className="mt-0.5">{designStatusLabel(design.status)}</dd>
                  </div>
                  <div>
                    <dt className="text-xs text-muted-foreground">Variation</dt>
                    <dd className="mt-0.5">#{design.variation_index + 1}</dd>
                  </div>
                  <div>
                    <dt className="text-xs text-muted-foreground">Provider</dt>
                    <dd className="mt-0.5">{design.provider} (mock)</dd>
                  </div>
                  <div>
                    <dt className="text-xs text-muted-foreground">Created</dt>
                    <dd className="mt-0.5">{formatDate(design.created_at)}</dd>
                  </div>
                  {projectName && (
                    <div className="col-span-2">
                      <dt className="text-xs text-muted-foreground">Product</dt>
                      <dd className="mt-0.5">{projectName}</dd>
                    </div>
                  )}
                </dl>

                <div>
                  <p className="text-xs font-medium text-muted-foreground">Prompt</p>
                  <p className="mt-1 max-h-32 overflow-y-auto rounded-lg bg-muted/50 p-3 text-xs whitespace-pre-wrap">
                    {design.prompt}
                  </p>
                </div>
                {design.negative_prompt && (
                  <div>
                    <p className="text-xs font-medium text-muted-foreground">Negative prompt</p>
                    <p className="mt-1 max-h-24 overflow-y-auto rounded-lg bg-muted/50 p-3 text-xs whitespace-pre-wrap">
                      {design.negative_prompt}
                    </p>
                  </div>
                )}
                {isFailed && design.error_message && (
                  <p className="rounded-lg bg-destructive/10 p-3 text-xs text-destructive" role="alert">
                    {design.error_message}
                  </p>
                )}
                {actionError && (
                  <p className="text-xs text-destructive" role="alert">
                    {actionError}
                  </p>
                )}
              </div>

              <DialogFooter>
                {isFailed && (
                  <Button type="button" variant="outline" onClick={handleRetry} disabled={isRetrying}>
                    {isRetrying && <Loader2 className="size-4 animate-spin" />}
                    <RotateCcw className="size-3.5" />
                    Retry
                  </Button>
                )}
                {!isFailed && (
                  <Button
                    type="button"
                    variant="outline"
                    disabled
                    className="opacity-70"
                    title="Regenerating a completed design arrives in Phase 6"
                  >
                    <RotateCcw className="size-3.5" />
                    Regenerate
                  </Button>
                )}
                <Button
                  type="button"
                  variant="outline"
                  disabled
                  className="opacity-70"
                  title="Downloads arrive once real generation produces final export-ready assets"
                >
                  <Download className="size-3.5" />
                  Download
                </Button>
                <Button type="button" variant="destructive" onClick={handleDelete} disabled={isDeleting}>
                  {isDeleting && <Loader2 className="size-4 animate-spin" />}
                  <Trash2 className="size-3.5" />
                  Delete
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>

          {isFailed && (
            <Button type="button" variant="outline" size="sm" onClick={handleRetry} disabled={isRetrying}>
              {isRetrying ? <Loader2 className="size-3.5 animate-spin" /> : <RotateCcw className="size-3.5" />}
              Retry
            </Button>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
